server:
  port: 8761


eureka:
  instance:
    hostname: "${HOST_NAME}.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false
    servceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}

